### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by swathida-byte** [mshick/add-pr-comment#46]
I updated the permissions in workflow file ,I'm getting this error only when the message has more than 50lines

**Comment by jritsema** [comment]
I just got the same thing.  Not sure if something else is required?

<img width="540" alt="image" src="https://user-images.githubusercontent.com/934927/187729980-7f769a67-02f5-4519-84e5-cdd8e6d19c4a.png">

**Comment by swathida-byte** [comment]
this action cannot be used if PR is raised from. forks

**Comment by jritsema** [comment]
Hi @swathida-byte, in my case, i was not raising the PR from a fork.  I needed to add a required permission to get things working.  I submitted a [PR](https://github.com/mshick/add-pr-comment/pull/48) in case it's helpful to others.

**Comment by mshick** [comment]
@swathida-byte Working with @jritsema to update the docs about the perms, but hopefully you got things working. It's true, this can't be used from forks, that's why there's the [proxy-url support](https://github.com/mshick/add-pr-comment#proxy-for-fork-based-prs). There might be other ways to accomplish that now as well, not totally sure. Thanks!
