### ISSUE TITLE
Error: Bad Request on Merge

### ISSUE THREAD

**Issue by ccapellan** [mshick/add-pr-comment#52]
I'm getting the exception "Error: Bad Request" when merging a pull request.

**Comment by ccapellan** [comment]
We're using GitHub AE in a hosted environment.  I see references in the code to api.github.com, so I'm guessing that could be the issue.

**Comment by mshick** [comment]
I bet that's it. Maybe there's a better way to get pulls now — when I wrote this the endpoint was experimental. I'll see what's available and hopefully can fix.

**Comment by mshick** [comment]
@ccapellan I replaced that experimental REST call against the github API with an octokit method. It was only for the situation where the event wasn't a PR event, so it is possible that was being called since you say this was a `merge` — maybe you were running it when the PR merged to master or something?

Otherwise, there are quite a few updates in `v2` so maybe you can test it out in your workflow and see if your issue is resolved?

**Comment by mshick** [comment]
Closing this issue for now. Please reopen if you're still having this issue.
