### ISSUE TITLE
Support pre-formatted text for `message-path`

### ISSUE THREAD

**Issue by TheArhaam** [mshick/add-pr-comment#73]
I'm currently using `add-pr-comment` for commenting out a report that is generated by my repo. The report is a table and the output of a console which must retain its formatting. 

I suggest adding the following options:
- Allow appending multiple messages to each other, that way I could add backticks within the configuration
- Adding in an option for code blocks: `code-block: true`

**Comment by mshick** [comment]
@TheArhaam Great point! Let me investigate and get back. TBH, I thought you could use backticks in the message, so I'll need to check out why that's not working.

**Comment by mshick** [comment]
@TheArhaam Ah, I think I understand your use case now — you're saying you have a `message-path` file, and you'd like to treat that file as pre-formatted text, rather than markdown? As a  workaround you could always pre-process your file in a previous action, something like:

```
- run: |
    echo '```' > ./newfile.txt
    cat myfile.txt >> ./newfile.txt
    echo '```' >> ./newfile.txt
```

If you can confirm that I have your use case correct though, I can add a pre-formatted type option to the action.

**Comment by mshick** [comment]
I've added that `preformatted` option, feel free to try it out and report back if you find it useful.
